name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Morphe patch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.7.1"
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle :patches:buildAndroid --no-daemon
      - name: Upload patch bundle
        uses: actions/upload-artifact@v4
        with:
          name: morph-patches
          path: patches/build/libs/*.mpp
